load("@rules_python//python:py_binary.bzl", "py_binary")

py_binary(
    name = "compare",
    srcs = ["compare.py"],
    deps = [
        "@pypi//chess",
    ],
)

py_binary(
    name = "sprt",
    srcs = ["sprt.py"],
)
